### ISSUE TITLE
Documentation should explain how to get each setting and their meaning

### ISSUE THREAD

**Issue by rngadam** [Prepsmith/circleci_webhook_listener#11]
Especially confused about circle_ci_url (I constructed it by myself, but be nice to have some place to copy it from) and port (port of what? the receiving port I imagine?).

**Comment by rngadam** [comment]
![screen shot 2016-12-07 at 10 47 27 am](https://cloud.githubusercontent.com/assets/538542/20952906/a9ab33fe-bc6a-11e6-85e0-84fa4663f4fc.png)

...found out there's a project specific settings. Do Build Artifacts only work?

**Comment by rngadam** [comment]
...shouldn't a webhook have a full URL for the callback (which is what I'm supposing is the port value here?)

**Comment by rngadam** [comment]
...add a diagram explaining the flow for the webhook

**Comment by rngadam** [comment]
...explain where the webhook is configured (circle.yml) and how those settings relate to this project.

**Comment by thimovss** [comment]
Created a [Pull request](https://github.com/Prepsmith/circleci_webhook_listener/pull/12)
