### ISSUE TITLE
add hostname to configuration spec instead of just port

### ISSUE THREAD

**Issue by rngadam** [Prepsmith/circleci_webhook_listener#14]
you should change this to not only request for port specification but also the IP to bind to. it's quite common to want to bind specifically to 127.0.0.1:port and then forward traffic to and from using a reverse proxy like nginx.

as it is:

```
If the hostname is omitted, the server will accept connections on any IPv6 address (::) when IPv6 is available, or any IPv4 address (0.0.0.0) otherwise
```

https://nodejs.org/api/http.html#http_server_listen_port_hostname_backlog_callback

not good if you care about securing or restricting access.

**Comment by thimovss** [comment]
created [pull request](https://github.com/Prepsmith/circleci_webhook_listener/pull/12)
