### ISSUE TITLE
Use cross-platform path separators

### ISSUE THREAD

**Issue by rngadam** [Prepsmith/circleci_webhook_listener#7]
use of backlash in tests is creating incorrect file paths.

![screen shot 2016-12-07 at 10 22 57 am](https://cloud.githubusercontent.com/assets/538542/20952427/4350e462-bc67-11e6-8527-6c5d2d955310.png)

Plus, shouldn't this be in a temporary directory?

**Comment by thimovss** [comment]
I implemented the path module this should resolve the issues. see [Branch issue 7](https://github.com/Prepsmith/circleci_webhook_listener/tree/issue_7_cross_platform_paths) if it didn't work please reopen the issue
